exports.migrate = (result) => {
  let newData = {};
  newData.removed = result.removed;
  newData.enabled = result.enabled;
  newData.branchs = result.branchs;
  newData.productCategory = result.productCategory;
  newData.suppliers = result.suppliers;
  newData.name = result.name;
  newData.description = result.description;
  newData.title = result.title;
  newData.tags = result.tags;
  newData.photo = result.photo;
  newData.headerImage = result.headerImage;
  newData.images = result.images;
  newData.files = result.files;
  newData.priceBeforeTax = result.priceBeforeTax;
  newData.taxRate = result.taxRate;
  newData.price = result.price;
  newData.customField = result.customField;
  newData.created = result.created;
  newData.updated = result.updated;
  newData.isPublic = result.isPublic;
  return newData;
};