const color = [
  { value: 'default', label: 'por defecto' },
  { value: 'magenta', label: 'magenta', color: 'magenta' },
  { value: 'red', label: 'rojo', color: 'red' },
  { value: 'volcano', label: 'volcánico', color: 'volcano' },
  { value: 'orange', label: 'naranja', color: 'orange' },
  { value: 'gold', label: 'oro', color: 'gold' },
  { value: 'lime', label: 'lima', color: 'lime' },
  { value: 'green', label: 'verde', color: 'green' },
  { value: 'cyan', label: 'cian', color: 'cyan' },
  { value: 'blue', label: 'azul', color: 'blue' },
  { value: 'geekblue', label: 'azul geek', color: 'geekblue' },
  { value: 'purple', label: 'púrpura', color: 'purple' },
  { value: '#F2BED1', label: 'rosa', color: '#F2BED1' },
  { value: '#222', label: 'negro', color: '#222' },
  { value: '#999', label: 'gris', color: '#999' },
  { value: '#31304D', label: 'gris oscuro', color: '#31304D' },
  { value: '#C69774', label: 'marrón', color: '#C69774' },
  { value: '#FFC436', label: 'amarillo', color: '#FFC436' },
  { value: '#637E76', label: 'verde oscuro', color: '#637E76' },
  { value: '#29ADB2', label: 'turquesa', color: '#29ADB2' },
  { value: '#FFAD84', label: 'coral', color: '#FFAD84' },
  { value: '#B6BBC4', label: 'plata', color: '#B6BBC4' },
  { value: '#392467', label: 'violeta', color: '#392467' },
  { value: '#A367B1', label: 'baya', color: '#A367B1' },
  { value: '#88AB8E', label: 'oliva', color: '#88AB8E' },
  { value: '#0F2167', label: 'azul marino', color: '#0F2167' },
  { value: '#4CB9E7', label: 'agua', color: '#4CB9E7' },
  { value: '#DED0B6', label: 'beige', color: '#DED0B6' },
  { value: '#8A2BE2', label: 'violeta azulado', color: '#8A2BE2' },
  { value: '#DEB887', label: 'madera de álamo', color: '#DEB887' },
  { value: '#5F9EA0', label: 'azul cadete', color: '#5F9EA0' },
  { value: '#D2691E', label: 'chocolate', color: '#D2691E' },
  { value: '#DC143C', label: 'carmesí', color: '#DC143C' },
  { value: '#00008B', label: 'azul oscuro', color: '#00008B' },
  { value: '#008B8B', label: 'cian oscuro', color: '#008B8B' },
  { value: '#B8860B', label: 'ocre oscuro', color: '#B8860B' },
  { value: '#A9A9A9', label: 'gris oscuro', color: '#A9A9A9' },
  { value: '#006400', label: 'verde oscuro', color: '#006400' },
  { value: '#BDB76B', label: 'caqui oscuro', color: '#BDB76B' },
  { value: '#8B008B', label: 'magenta oscuro', color: '#8B008B' },
  { value: '#556B2F', label: 'verde oliva oscuro', color: '#556B2F' },
  { value: '#FF8C00', label: 'naranja oscuro', color: '#FF8C00' },
  { value: '#9932CC', label: 'orquídea oscuro', color: '#9932CC' },
  { value: '#C70039', label: 'rojo oscuro', color: '#C70039' },
  { value: '#E9967A', label: 'salmón oscuro', color: '#E9967A' },
  { value: '#8FBC8F', label: 'verde mar oscuro', color: '#8FBC8F' },
  { value: '#483D8B', label: 'azul pizarra oscuro', color: '#483D8B' },
  { value: '#2F4F4F', label: 'gris pizarra oscuro', color: '#2F4F4F' },
  { value: '#00CED1', label: 'turquesa oscuro', color: '#00CED1' },
  { value: '#9400D3', label: 'violeta oscuro', color: '#9400D3' },
  { value: '#FF1493', label: 'rosa profundo', color: '#FF1493' },
  { value: '#00BFFF', label: 'azul cielo profundo', color: '#00BFFF' },
  { value: '#696969', label: 'gris apagado', color: '#696969' },
  { value: '#1E90FF', label: 'azul esquiva', color: '#1E90FF' },
];

export default color;
